# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.chain_lock.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'chain_lock', 'function_path': 'animated_java:chain_lock/variants/default/apply'}
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain13] run function animated_java:chain_lock/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain14] run function animated_java:chain_lock/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain15] run function animated_java:chain_lock/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain16] run function animated_java:chain_lock/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain9] run function animated_java:chain_lock/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain10] run function animated_java:chain_lock/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain11] run function animated_java:chain_lock/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain12] run function animated_java:chain_lock/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain5] run function animated_java:chain_lock/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain6] run function animated_java:chain_lock/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain7] run function animated_java:chain_lock/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain8] run function animated_java:chain_lock/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain4] run function animated_java:chain_lock/variants/default/zzz/12
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain3] run function animated_java:chain_lock/variants/default/zzz/13
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain2] run function animated_java:chain_lock/variants/default/zzz/14
execute on passengers if entity @s[tag=aj.chain_lock.bone.chain] run function animated_java:chain_lock/variants/default/zzz/15