# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.su_boss.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'su_boss', 'function_path': 'animated_java:su_boss/animations/kill/stop'}
tag @s remove aj.su_boss.animation.kill.playing
scoreboard players set @s aj.kill.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:su_boss/animations/kill/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only