# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hill.root] run return 0
execute on passengers if entity @s[tag=aj.hill.data] unless data entity @s {data:{rigHash: 'b1ab090b187db84816c3fc9b48a81e0f16515b6c028c06c1af4c4a70ed251d8f'}} on vehicle run function animated_java:hill/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1