# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.soulbreaker.root] run return 0
execute on passengers if entity @s[tag=aj.soulbreaker.data] unless data entity @s {data:{rigHash: '8d915e09e004f63d071a4f79d6cdee38af31752f2f4639fe427fdeb6111a389a'}} on vehicle run function animated_java:soulbreaker/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1