# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.soulbreaker.root] run return 0
execute on passengers if entity @s[tag=aj.soulbreaker.data] unless data entity @s {data:{rigHash: '65cdb5a4ebbcf0d256c30ab7b77c86f3a92b2757138282f3b02994440f6ea208'}} on vehicle run function animated_java:soulbreaker/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1