# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.test.root] run return 0
execute on passengers if entity @s[tag=aj.test.data] unless data entity @s {data:{rigHash: '13be374c86fc5946772f04fd1d49a88e0d4cb5b0a3395f882905a424dec012bd'}} on vehicle run function animated_java:test/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1