# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chest.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:chest/as_root/pre_tick
execute if entity @s[tag=aj.chest.animation.idle.playing] run function animated_java:chest/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.chest.animation.open.playing] run function animated_java:chest/animations/open/zzz/on_tick
execute on passengers if entity @s[tag=aj.chest.data] run function animated_java:chest/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:chest/as_root/post_tick