# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_leftleg) { transformation: [1f,0f,0f,-0.11875f,0f,1f,0f,0.75f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_rightleg) { transformation: [1f,0f,0f,0.11875f,0f,1f,0f,0.75f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_leftarm) { transformation: [1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_rightarm) { transformation: [1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_body) { transformation: [1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_head) { transformation: [1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }