# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:block.anvil.place voice @a ~ ~1 ~ 1 1
particle block{block_state:"minecraft:yellow_stained_glass"} ~ ~1 ~ 1 1 1 1 200 normal