# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:block.respawn_anchor.deplete voice @a ~ ~1 ~ 1 1.5
particle minecraft:flash ~ ~1 ~ 0 0 0 0 1
playsound minecraft:block.trial_spawner.about_to_spawn_item voice @p ~ ~1 ~ 9999 0.75
effect give @p minecraft:slowness 5 3 true
attribute @p minecraft:generic.jump_strength modifier add chain_lock -0.99 add_multiplied_base