# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle dust_color_transition{from_color:[1.000,0.000,0.000],scale:1.5,to_color:[0.000,0.000,0.000]} ~ ~1 ~ 1 1 1 1 10 normal
playsound minecraft:block.beacon.ambient voice @a ~ ~1 ~ 3 1
particle minecraft:trial_spawner_detection ~ ~ ~ 0.5 0.5 0.5 0 20