# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:su_boss/remove/all
execute rotated 0 0 in game_map:ancient_lorras positioned 10000 60 10000 run function animated_java:su_boss_2/summon/default