# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:portal ~ ~1 ~ 0 0 0 5 400
stopsound @a[distance=..20] voice minecraft:block.beacon.ambient
playsound minecraft:block.beacon.power_select voice @a ~ ~ ~ 3 0.75
playsound minecraft:block.beacon.activate voice @a ~ ~1 ~ 3 2