# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:explosion_emitter ~ ~1 ~ 0 0 0 0 1 normal @a
function animated_java:boss_display/animations/idle/play
playsound minecraft:block.respawn_anchor.set_spawn voice @a ~ ~ ~ 3 0.5
playsound minecraft:entity.zombie_villager.cure voice @a ~ ~ ~ 1 0.75