# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rajeta.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rajeta', 'function_path': 'animated_java:rajeta/animations/pause_all'}
tag @s remove aj.rajeta.animation.idle.playing
tag @s remove aj.rajeta.animation.attack1.playing
tag @s remove aj.rajeta.animation.walk.playing