# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.flash_crystal.root] run return 0
execute on passengers if entity @s[tag=aj.flash_crystal.data] unless data entity @s {data:{rigHash: '69262c02d341b15f1e943d90cb6d0f5b0868c7d552371ea985d052ca42fc2c5c'}} on vehicle run function animated_java:flash_crystal/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1