# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.flash_crystal.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:flash_crystal/as_root/pre_tick
execute if entity @s[tag=aj.flash_crystal.animation.idle.playing] run function animated_java:flash_crystal/animations/idle/zzz/on_tick
execute on passengers if entity @s[tag=aj.flash_crystal.data] run function animated_java:flash_crystal/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
execute on vehicle unless data entity @s {DeathTime:0s} on passengers at @s run function monsters:flash_crystal/remove_display
function #animated_java:flash_crystal/as_root/post_tick