# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.su_boss_2.root] run return 0
execute on passengers if entity @s[tag=aj.su_boss_2.data] unless data entity @s {data:{rigHash: '224fc6a4b3df485fa853572b0fce1af55beade631ed215889aa3c4adc4f22834'}} on vehicle run function animated_java:su_boss_2/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1