# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rajeta.root] run return 0
execute on passengers if entity @s[tag=aj.rajeta.data] unless data entity @s {data:{rigHash: '85bd59316eaeebe24d65f264c3e37f6270a505f7a18548802274d7eeabc69566'}} on vehicle run function animated_java:rajeta/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1