# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rajeta.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:rajeta/as_root/pre_tick
execute if entity @s[tag=aj.rajeta.animation.idle.playing] run function animated_java:rajeta/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.rajeta.animation.attack1.playing] run function animated_java:rajeta/animations/attack1/zzz/on_tick
execute if entity @s[tag=aj.rajeta.animation.walk.playing] run function animated_java:rajeta/animations/walk/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:rajeta/as_root/post_tick