# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.su_boss.root] run return 0
execute on passengers if entity @s[tag=aj.su_boss.data] unless data entity @s {data:{rigHash: '97d0582847ceaee73e0bd25595b30ce4e44bba558062dd35ae8236931decbd49'}} on vehicle run function animated_java:su_boss/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1