# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.soulbreaker.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'soulbreaker', 'function_path': 'animated_java:soulbreaker/variants/default/apply'}
execute on passengers if entity @s[tag=aj.soulbreaker.bone.layer] run function animated_java:soulbreaker/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.soulbreaker.bone.head] run function animated_java:soulbreaker/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.soulbreaker.bone.6] run function animated_java:soulbreaker/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.soulbreaker.bone.5] run function animated_java:soulbreaker/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.soulbreaker.bone.10] run function animated_java:soulbreaker/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.soulbreaker.bone.9] run function animated_java:soulbreaker/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.soulbreaker.bone.2] run function animated_java:soulbreaker/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.soulbreaker.bone.1] run function animated_java:soulbreaker/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.soulbreaker.bone.4] run function animated_java:soulbreaker/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.soulbreaker.bone.3] run function animated_java:soulbreaker/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.soulbreaker.bone.8] run function animated_java:soulbreaker/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.soulbreaker.bone.7] run function animated_java:soulbreaker/variants/default/zzz/11