# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chris.root] run return 0
execute on passengers if entity @s[tag=aj.chris.data] unless data entity @s {data:{rigHash: '9531f1e0e3abf1471c6c862bfeb1ad877e9e3c09ad73a6a7f197a5db37565cca'}} on vehicle run function animated_java:chris/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1