# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.boss_display.root] run return 0
execute on passengers if entity @s[tag=aj.boss_display.data] unless data entity @s {data:{rigHash: 'd95c6788584f3d21934d6b58e7a9521b40979ed45c694eee748d3f00a3a8f422'}} on vehicle run function animated_java:boss_display/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1