# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.boss_display.root] run return 0
execute on passengers if entity @s[tag=aj.boss_display.data] unless data entity @s {data:{rigHash: '070d6cd7f7b82c76b56c81a10a6424bde39888d008afe70ceb6fe923c98d2421'}} on vehicle run function animated_java:boss_display/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1