# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.chain_lock.root] run return 0
execute on passengers if entity @s[tag=aj.chain_lock.data] unless data entity @s {data:{rigHash: 'a6dd70738c439b0e6c8f22e16f21fd912d1b97c73efbc40b47a6c349cfec97dc'}} on vehicle run function animated_java:chain_lock/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1