# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.boss_display.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'boss_display', 'function_path': 'animated_java:boss_display/variants/default/apply'}
execute on passengers if entity @s[tag=aj.boss_display.bone.leftleg] run function animated_java:boss_display/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.boss_display.bone.rightleg] run function animated_java:boss_display/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.boss_display.bone.leftarm] run function animated_java:boss_display/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.boss_display.bone.rightarm] run function animated_java:boss_display/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.boss_display.bone.body] run function animated_java:boss_display/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.boss_display.bone.head] run function animated_java:boss_display/variants/default/zzz/5