# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.data] run function animated_java:su_boss/zzz/1
tag @s remove aj.new
execute if data storage aj:temp args.variant run function animated_java:su_boss/zzz/2 with storage aj:temp args
execute unless data storage aj:temp args.animation run function animated_java:su_boss/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:su_boss/zzz/6 with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s add su_boss.animation
function animated_java:su_boss/animations/kill/play
playsound minecraft:item.trident.riptide_1 voice @a ~ ~ ~ 1 0.5
playsound minecraft:entity.generic.explode voice @a ~ ~ ~ 1 1.25
playsound minecraft:block.anvil.place voice @a ~ ~ ~ 1 1
particle minecraft:flame ~ ~1 ~ 0 0 0 0.25 10
particle minecraft:flash ~ ~1 ~ 0 0 0 0 2 normal @a
function #animated_java:su_boss/as_root/on_summon